### ISSUE TITLE
✅ [23.03.13] 로그인 페이지 마크업 및 데이터 모델링, 유저플로우 작업

### ISSUE THREAD

**Issue by hungerbk** [likelion4th-React-LAB15/final-project#3]
## 작업 사항

로그인 페이지 마크업 및 데이터 모델링, 유저플로우 작업

## Todo
- [x] 로그인 페이지 마크업
- [x] 데이터 모델링 다이어그램 완성
- [x] 유저플로우 완성

**Comment by ovelute53** [comment]
## 유저플로우

<img width="5362" alt="user flow" src="https://user-images.githubusercontent.com/104200167/224744707-5548ce1f-d628-4538-8198-ee961460f4ec.png">


## 데이터 모델링
<img width="2512" alt="데이터 모델링" src="https://user-images.githubusercontent.com/104200167/224744746-1c1c2e08-f12c-43a0-ad77-81a0550110e7.png">
